name: Build and publish bgmdatapostprocess image

on:
  push:
    paths:
    - 'postprocess/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build postprocess --tag image
    - name: Log into registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u wattlebird --password-stdin
    - name: Push image
      run: |
        docker tag image wattlebird/bgmdatapostprocess:latest
        docker push wattlebird/bgmdatapostprocess:latest
