name: Deploy spiders

on:
  #schedule:
    # * is a special character in YAML so you have to quote this string
  #  - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Redeploy scrapyd image
      run: doctl apps create-deployment 919b7d00-56d2-4fad-a7ec-49ac08fecfba
    - name: Wait for image running
      run: sleep 150s
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scrapy scrapyd
    - name: Update configure files
      run: |
        sed -i 's~^UPLOAD_TO_AZURE_STORAGE = False$~UPLOAD_TO_AZURE_STORAGE = True~g' bgm/settings.py
        sed -i 's~^UPLOAD_TO_AZURE_STORAGE = False$~UPLOAD_TO_AZURE_STORAGE = True~g' bgmapi/settings.py
        sed -i 's~^AZURE_ACCOUNT_KEY = ""$~AZURE_ACCOUNT_KEY = "${{ secrets.AZURE_BLOB_KEY }}"~g' bgm/settings.py
        sed -i 's~^AZURE_ACCOUNT_KEY = ""$~AZURE_ACCOUNT_KEY = "${{ secrets.AZURE_BLOB_KEY }}"~g' bgmapi/settings.py
    - name: Deploy bgmapi
      run: |
        python setup_bgmapi.py bdist_egg
        curl --user ike:${{ secrets.SCRAPYD_PASSWORD }} https://whale-app-qrnck.ondigitalocean.app/addversion.json -F project=bgmapi -F version=1.0 -F egg=@dist/project-1.0-py3.10.egg
    - name: Create jobs
      run: |
        curl --user ike:${{ secrets.SCRAPYD_PASSWORD }} https://whale-app-qrnck.ondigitalocean.app/schedule.json -d project=bgmapi -d spider=subject-api -d id_max=450000 -d token=${{ secrets.BANGUMI_TOKEN }}
        curl --user ike:${{ secrets.SCRAPYD_PASSWORD }} https://whale-app-qrnck.ondigitalocean.app/schedule.json -d project=bgmapi -d spider=collections-api -d id_max=800000